version: '2'

services:
  app:
    build: .
    container_name: review-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/review
      SPRING_DATASOURCE_USERNAME: review
      SPRING_DATASOURCE_PASSWORD: review

  db:
    image: 'postgres:15-alpine'
    container_name: review-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: review
      POSTGRES_USER: review
      POSTGRES_PASSWORD: review

volumes:
  postgres_data: {}